import {commentId1, commentId2} from './FakeCommentData';

const articleList = [
  {
    groupTitle: 'About nothing',
    groupIndex: 0,
    description: 'About nothing at all',
    icon: '/img/logo.png',
    nShow: 6,
    date: 0,
    id: undefined,
    itemList: [{
      groupTitle: 'About tensorflow',
      groupIndex: 0,
      commentId: commentId1,
      author: 'pd',
      nView: 12,
      nComment: 0,
      index: 0,
      imgSrc: "http://p3ijxxb1r.bkt.clouddn.com/test-167795.jpg?imageView2/1/w/200/h/250/format/png/q/75|imageslim",
      textSrc: 'This is the text source',
      date: 0,
      title: "A demo article",
      description: "The description of a demo article",
    }, {
      groupTitle: 'About tensorflow',
      groupIndex: 0,
      commentId: commentId1,
      author: 'pd',
      nView: 12,
      nComment: 0,
      index: 1,
      imgSrc: "http://p3ijxxb1r.bkt.clouddn.com/test-167795.jpg?imageView2/1/w/200/h/250/format/png/q/75|imageslim",
      textSrc: 'This is another text source',
      date: 1,
      title: "Another demo article",
      description: "The description of the second demo article"
    }, {
      groupTitle: 'About tensorflow',
      groupIndex: 0,
      commentId: commentId1,
      author: 'pd',
      nView: 12,
      nComment: 0,
      index: 2,
      imgSrc: "http://p3ijxxb1r.bkt.clouddn.com/test-167795.jpg?imageView2/1/w/200/h/250/format/png/q/75|imageslim",
      textSrc: 'This is the text source',
      date: 0,
      title: "A demo article",
      description: "The description of a demo article"
    }, {
      groupTitle: 'About tensorflow',
      groupIndex: 0,
      commentId: commentId1,
      author: 'pd',
      nView: 12,
      nComment: 0,
      index: 3,
      imgSrc: "http://p3ijxxb1r.bkt.clouddn.com/test-167795.jpg?imageView2/1/w/200/h/250/format/png/q/75|imageslim",
      textSrc: 'This is another text source',
      date: 1,
      title: "Another demo article",
      description: "The description of the second demo article"
    }, {
      groupTitle: 'About tensorflow',
      groupIndex: 0,
      commentId: commentId1,
      author: 'pd',
      nView: 12,
      nComment: 0,
      index: 4,
      imgSrc: "http://p3ijxxb1r.bkt.clouddn.com/test-167795.jpg?imageView2/1/w/200/h/250/format/png/q/75|imageslim",
      textSrc: 'This is the text source',
      date: 0,
      title: "A demo article",
      description: "The description of a demo article"
    }, {
      groupTitle: 'About tensorflow',
      groupIndex: 0,
      commentId: commentId1,
      author: 'pd',
      nView: 12,
      nComment: 0,
      index: 5,
      imgSrc: "http://p3ijxxb1r.bkt.clouddn.com/test-167795.jpg?imageView2/1/w/200/h/250/format/png/q/75|imageslim",
      textSrc: 'This is another text source',
      date: 1,
      title: "Another demo article",
      description: "The description of the second demo article"
    }, {
      groupTitle: 'About tensorflow',
      groupIndex: 0,
      commentId: commentId1,
      author: 'pd',
      nView: 12,
      nComment: 0,
      index: 6,
      imgSrc: "http://p3ijxxb1r.bkt.clouddn.com/test-167795.jpg?imageView2/1/w/200/h/250/format/png/q/75|imageslim",
      textSrc: 'This is the text source',
      date: 0,
      title: "A demo article",
      description: "The description of a demo article"
    }, {
      groupTitle: 'About tensorflow',
      groupIndex: 0,
      commentId: commentId1,
      author: 'pd',
      nView: 12,
      nComment: 0,
      index: 7,
      imgSrc: "http://p3ijxxb1r.bkt.clouddn.com/test-167795.jpg?imageView2/1/w/200/h/250/format/png/q/75|imageslim",
      textSrc: 'This is another text source',
      date: 1,
      title: "Another demo article",
      description: "The description of the second demo article"
    }]
  },
  {
    groupTitle: 'About tensorflow',
    groupIndex: 1,
    description: 'Knowledge about tensorflow',
    icon: '/img/logo.png',
    nShow: 6,
    date: 0,
    id: undefined,
    itemList: [{
      groupTitle: 'About tensorflow',
      groupIndex: 0,
      commentId: commentId2,
      author: 'pd',
      nView: 12,
      nComment: 0,
      index: 0,
      imgSrc: "http://p3ijxxb1r.bkt.clouddn.com/test-167795.jpg?imageView2/1/w/200/h/250/format/png/q/75|imageslim",
      textSrc: 'This is the text source',
      date: 0,
      title: "A demo article",
      description: "The description of a demo article",
    }, {
      groupTitle: 'About tensorflow',
      groupIndex: 0,
      commentId: commentId2,
      author: 'pd',
      nView: 12,
      nComment: 0,
      index: 1,
      imgSrc: "http://p3ijxxb1r.bkt.clouddn.com/test-167795.jpg?imageView2/1/w/200/h/250/format/png/q/75|imageslim",
      textSrc: 'This is another text source',
      date: 1,
      title: "Another demo article",
      description: "The description of the second demo article"
    }, {
      groupTitle: 'About tensorflow',
      groupIndex: 0,
      commentId: commentId2,
      author: 'pd',
      nView: 12,
      nComment: 0,
      index: 2,
      imgSrc: "http://p3ijxxb1r.bkt.clouddn.com/test-167795.jpg?imageView2/1/w/200/h/250/format/png/q/75|imageslim",
      textSrc: 'This is the text source',
      date: 0,
      title: "A demo article",
      description: "The description of a demo article"
    }, {
      groupTitle: 'About tensorflow',
      groupIndex: 0,
      commentId: commentId2,
      author: 'pd',
      nView: 12,
      nComment: 0,
      index: 3,
      imgSrc: "http://p3ijxxb1r.bkt.clouddn.com/test-167795.jpg?imageView2/1/w/200/h/250/format/png/q/75|imageslim",
      textSrc: 'This is another text source',
      date: 1,
      title: "Another demo article",
      description: "The description of the second demo article"
    }, {
      groupTitle: 'About tensorflow',
      groupIndex: 0,
      commentId: commentId2,
      author: 'pd',
      nView: 12,
      nComment: 0,
      index: 4,
      imgSrc: "http://p3ijxxb1r.bkt.clouddn.com/test-167795.jpg?imageView2/1/w/200/h/250/format/png/q/75|imageslim",
      textSrc: 'This is the text source',
      date: 0,
      title: "A demo article",
      description: "The description of a demo article"
    }, {
      groupTitle: 'About tensorflow',
      groupIndex: 0,
      commentId: commentId2,
      author: 'pd',
      nView: 12,
      nComment: 0,
      index: 5,
      imgSrc: "http://p3ijxxb1r.bkt.clouddn.com/test-167795.jpg?imageView2/1/w/200/h/250/format/png/q/75|imageslim",
      textSrc: 'This is another text source',
      date: 1,
      title: "Another demo article",
      description: "The description of the second demo article"
    }, {
      groupTitle: 'About tensorflow',
      groupIndex: 0,
      commentId: commentId2,
      author: 'pd',
      nView: 12,
      nComment: 0,
      index: 6,
      imgSrc: "http://p3ijxxb1r.bkt.clouddn.com/test-167795.jpg?imageView2/1/w/200/h/250/format/png/q/75|imageslim",
      textSrc: 'This is the text source',
      date: 0,
      title: "A demo article",
      description: "The description of a demo article"
    }, {
      groupTitle: 'About tensorflow',
      groupIndex: 0,
      commentId: commentId2,
      author: 'pd',
      nView: 12,
      nComment: 0,
      index: 7,
      imgSrc: "http://p3ijxxb1r.bkt.clouddn.com/test-167795.jpg?imageView2/1/w/200/h/250/format/png/q/75|imageslim",
      textSrc: 'This is another text source',
      date: 1,
      title: "Another demo article",
      description: "The description of the second demo article"
    }]
  }
];

export default articleList;
